---
version: 2.1

workflows:
  version: 2.1
  validate_test_deploy:
    jobs:
      - validate_cm
      - validate_iac

executors:  
  ansible:
    docker:
      - image: "quay.io/ansible/molecule:2.22"
  terraform:
    docker: 
      - image: "hashicorp/terraform:light"

jobs:
  validate_cm:
    executor: ansible
    parameters:
      working_directory: 
        description: working directory
        type: string
        default: ./
      inventory:
        description: define inventory
        type: string
        default: inventory
      playbook: 
        description: define playbook
        type: string
        default: main.yml
    steps:
      - checkout
      - run:
          name: "YAMl Linting"
          command: yamllint .
          working_directory: << parameters.working_directory >>
      - run:
          name: "Ansible Linting"
          command: ansible-lint << parameters.playbook >>
          working_directory: << parameters.working_directory >>
      - run:
          name: "Ansible Syntax Check"
          command: ansible-playbook -i << parameters.inventory >> << parameters.playbook >> --syntax-check
          working_directory: << parameters.working_directory >>

  validate_iac:
    executor: terraform
    parameters:
      working_directory: 
        description: working directory
        type: string
        default: ./iac
    working_directory: << parameters.working_directory >>
    steps:
      - checkout
      - run:
          name: "terraform init"
          command: terraform init
      - run:
          name: "terraform validate"
          command: terraform validate
      - run:
          name: "terraform plan"
          command: terraform plan

  exec_iac:
    executor: terraform
    parameters:
      working_directory: 
        description: working directory
        type: string
        default: ./iac
      destroy: 
        description: destroy infrastructure if needed
        type: boolean
        default: false
    working_directory: << parameters.working_directory >>
    steps:
      - checkout
      - run:
          name: "Initialize"
          command: terraform init
      - run:
          name: "Planning Infrastructure changes"
          command: terraform plan <<# parameters.destroy >>destroy <</ parameters.destroy >>-out terraform.tfplan
      - run:
          name: "Apply Infrastructure changes"
          command: terraform apply -input=false terraform.tfplan

  exec_cm:
    executor: ansible
    parameters:
      working_directory: 
        description: working directory
        type: string
        default: ./
      inventory:
        description: define inventory
        type: string
        default: inventory
      playbook: 
        description: define playbook
        type: string
        default: main.yml
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "80:5f:c6:dc:47:20:80:1f:7b:bf:63:f2:bc:b7:24:a1"
      - run:
          name: "Ansible Syntax Check"
          command: ansible-playbook -i << parameters.inventory >> << parameters.playbook >> --syntax-check
          working_directory: << parameters.working_directory >>
