---

DOCKER_SWARM:
  vars:
    os: COREOS
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  children:

    DOCKER_SWARM_MANAGER:
      vars:
        dockerswarm_nodetype: "manager"
      hosts:
        control.do.ccbash.de:
          dockerswarm_labels:
            'ccbash.environment': "{{environment}}"

    DOCKER_SWARM_WORKER:
      vars:
        dockerswarm_nodetype: "worker"
      hosts:
        docker1.do.ccbash.de:
          dockerswarm_labels:
            'ccbash.environment': "{{environment}}"
